language: python

python:
    - "2.7"

sudo: false

install:
    - pip2.7 install --upgrade pip
    - pip2.7 --version
    - pip2.7 install numpy
    - pip2.7 install matplotlib
    - pip2.7 install pandas
    - pip2.7 install scipy
    - pip2.7 install sklearn
    - pip2.7 install requests

before_script:
    - uname -a
    - printenv
    - pip2.7 list

script:
    - date
    - ls -al
    - make test
